export enum MESSAGE_TYPES {
    HELLO_RECEIVED = 0,
    SEND_HELLO = 1,
    PEERS_REQUEST = 2,
    PEERS_RECEIVED = 3,
    REQUEST_PEERS = 4,
    CHAINTIP_REQUEST = 5,
    CHAINLENGTH_REQUEST = 6,
    CHAINTIP_RECEIVED = 7,
    REQUEST_CHAINTIP = 8,
    MEMPOOL_REQUEST = 9,
    MEMPOOL_RECEIVED = 10,
    REQUEST_MEMPOOL = 11,
    OBJECT_REQUEST = 12,
    BLOCK_RECEIVED = 13,
    TRANSACTION_RECEIVED = 14,
    COINBASE_RECEIVED = 15,
    REQUEST_OBJECT = 16,
    HAS_OBJECT = 17,
    ERROR_RECEIVED = 18,
}

export enum INVALID_TYPES {
    INVALID_FORMAT = 19,
    INTERNAL_ERROR = 20,
    UNKNOWN_OBJECT = 21,
    UNFINDABLE_OBJECT = 22,
    INVALID_HANDSHAKE = 23,
    INVALID_TX_OUTPOINT = 24,
    INVALID_TX_SIGNATURE = 25,
    INVALID_TX_CONSERVATION = 26,
    INVALID_BLOCK_COINBASE = 27,
    INVALID_BLOCK_TIMESTAMP = 28,
    INVALID_BLOCK_POW = 29,
    INVALID_GENESIS = 30,
    INVALID_MESSAGE = 31,
}

export enum OBJECT_TYPES {
    BLOCK_TYPE = 32,
    TRANSACTION_TYPE = 33,
    COINBASE_TYPE = 34,
    INVALID_OBJECT = 35,
}

export interface UTXO {
    outpoint_id: string;
    idx: number;
}